### ISSUE TITLE
Forks do not get updates from bot. Manual shows error response

### ISSUE THREAD

**Issue by onap-sdc** [backstrokeapp/server#105]
Hi,
Been using this for quite a while, with pleasure :). Recently noticed that the forks marked with label are not being updated. Tried to run the sync on demand link from the backstroke website manually and got the following error:

{"error":"EXECABORT Transaction discarded because of previous errors.","stack":"ReplyError: EXECABORT Transaction discarded because of previous errors.\n    at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)\n    at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)"}

Any idea what could be the issue?
Thanks

**Comment by 1egoman** [comment]
@onap-sdc Please see https://github.com/backstrokeapp/server#i-dont-have-the-bandwidth-to-maintain-backstroke-anymore, this project is in the process of being shut down
