### ISSUE TITLE
Pass a user to the proper private or public login link

### ISSUE THREAD

**Issue by 1egoman** [backstrokeapp/server#17]
If a user has private repos registered, they need to login via `/setup/login/private` for them to work.

**Comment by 1egoman** [comment]
As a workaround, everyone signs in with both "priviliges". May not be the best, though.

**Comment by karlhorky** [comment]
Is there a manual way to sign in with just public privileges?

**Comment by 1egoman** [comment]
@karlhorky There is, though it's undocumented. You should be able to head to https://backstroke.us/setup/login/public (instead of the normal https://backstroke.us/setup/login) to just grant backstroke the `public_repo` permission on github. Code is https://github.com/1egoman/backstroke/blob/master/src/server.js#L58


*WARNING*: I'm not supporting this endpoint officially. It may continue to work for a while (it's residual from a previous feature) or it may go away tomorrow.

**Comment by karlhorky** [comment]
Cool, that sounds good, thanks for the info!

Once this issue is completed (both private and public flow available), would you be open to supporting this endpoint again?

**Comment by 1egoman** [comment]
@karlhorky Possibly. I added the endpoint out of experimentation. If there's demand for something like this I can explore it, but it adds some complexity since I'd need to handle cases where a user didn't give Backstroke permission to access a repository, how to upgrade permissions, storing a user's permission level, etc.

**Comment by 0xCMP** [comment]
+1 for a clear way to both.

Please provide a public/private way to setup Backstroke. We have the permissions features of Github to prevent access to the repos so I'd rather not risk our internal code to sync our public forks.

As you said it makes things complicated, especially for making it a "just works" and auto upgrade experience, but I believe it's an important feature.

**Comment by 1egoman** [comment]
Moving to https://github.com/backstrokeapp/server/issues/7. Now that I have #66 released, my hope is that I can find a way to do this nicely.
