### ISSUE TITLE
Hmm, you cannot login screen is too short.

### ISSUE THREAD

**Issue by 1egoman** [backstrokeapp/server#26]
<img width="1129" alt="screen shot 2016-09-26 at 6 51 43 pm" src="https://cloud.githubusercontent.com/assets/1704236/18854556/51674f94-841a-11e6-8740-52a043eec54c.png">

Just needs a `height: 100%` on the container.

**Comment by c0n5pir4cy** [comment]
I'll have a look and see if I can fix this one.

**Comment by mitesh-mutha** [comment]
@1egoman Came across this issue via Hacktoberfest. Shall I pick it up if in case @c0n5pir4cy  isn't ?

**Comment by 1egoman** [comment]
@mitesh-mutha Yea, go for it. Instructions to set up/run Backstroke locally: https://github.com/1egoman/backstroke/blob/master/CONTRIBUTING.md#setting-up-backstroke-for-development

**Comment by mitesh-mutha** [comment]
@1egoman Thanks ! 
Will ask if I have any trouble. 
First step would be to setup to run Backstroke locally.

**Comment by 1egoman** [comment]
Fixed by https://github.com/backstrokeapp/server/issues/66
