### ISSUE TITLE
Tracking issue for manual upstream setting

### ISSUE THREAD

**Issue by jasonkarns** [backstrokeapp/server#3]

**Comment by 1egoman** [comment]
@jasonkarns I'll take a look at implementing custom upstreams this weekend. I'm thinking something like specifying on a fork a webhook like `http://backstroke.us?upstream=user/upstream`. Does that fit your use case?

**Comment by jasonkarns** [comment]
I think it would!

**Comment by 1egoman** [comment]
@jasonkarns Give custom upstreams a try with what's live right now (usage is how I described above). Keep in mind that they may still be a little (lotta?) buggy;

**Comment by jasonkarns** [comment]
Got an error :(

Added the webhook to https://github.com/nodenv/node-build as http://backstroke.us?upstream=rbenv/ruby-build and got: 

> Uhh, error: Error: The repository nodenv/node-build isn't a fork.

**Comment by 1egoman** [comment]
@jasonkarns Hmm, it looks like Github won't let a PR be created between two unrelated repos. If you can think of a workaround, I'll see what I can do but otherwise I'm unsure if I can make this work as you were thinking.

**Comment by simenbrekken** [comment]
@1egoman Any idea what identifies a "related repo"?

**Comment by 1egoman** [comment]
@simenbrekken From my understanding, two repos are related if they both share a common upstream at some point or are a common upstream. For example, if I have repo a and repo b, and repo c is a fork of repo a, then repo a and c are related, and repo b isn't. In addition, if I made a fork of repo c to repo d, repo a, c, and d are all related, while repo b still isn't.

Sorry if that was confusing, let me know if you'd like clarification.

**Comment by 1egoman** [comment]
Since this is a Github limitation and there's nothing I can do about it, going to close this.
