### ISSUE TITLE
automatically periodically hook

### ISSUE THREAD

**Issue by dsslimshaddy** [backstrokeapp/server#58]
currently i use https://ifttt.com/ to hook every hour. if backstroke could do it automatically it would be great

**Comment by 1egoman** [comment]
@dsslimshaddy I don't see this as something that I'd implement in the near term. If either you or anyone else wants to try this out, [start with this branch](https://github.com/1egoman/backstroke/tree/fix-it-all) and I'd be glad to look at pull requests.

**Comment by 1egoman** [comment]
Fixed by https://github.com/backstrokeapp/server/issues/66
