### ISSUE TITLE
It keeps saying `Server error` all the time on backstroke.us

### ISSUE THREAD

**Issue by evandrocoan** [backstrokeapp/server#63]
Recently for all git repositories I am registering, it is saying git error:

![image](https://user-images.githubusercontent.com/5332158/28997949-239d8e7e-79f7-11e7-8426-19195dcee849.png)

![back](https://user-images.githubusercontent.com/5332158/28997959-4f43d7f4-79f7-11e7-8c17-877e868d86b0.gif)

But if I go to the main page clicking on the `Links` button, the hook is on:

![image](https://user-images.githubusercontent.com/5332158/28997967-6f24bf66-79f7-11e7-8b23-1c005802aefd.png)

**Comment by 1egoman** [comment]
That's weird. Looks like the logs mention that some sort of rate limit from github's end (for your user token) was reached. Where you doing something that called backstroke repeatedly?

**Comment by evandrocoan** [comment]
No, I was not using the github api, or calling backstroke URLs at the moment, or any time near it. Perhaps, you could put this full message on the website instead of just `Server error`.

**Comment by 1egoman** [comment]
Hmm, let me investigate. I've made that change (more descriptive error messages) in the latest code, will be live next time I deploy.

**Comment by stevenambs** [comment]
I was getting this as well trying to link to a forked repo in one of my organizations. I transferred the fork out of the organization to my personal account and it works now.

**Comment by mithereal** [comment]
i was having the issue as well what fixed it for me was to go to the organizations settings 3rd party access and i removed the application restrictions

**Comment by 1egoman** [comment]
Huh. What application restrictions are you referring to? Maybe that would help reveal the source of the problem? I can't seem to find the options you are referring to.

**Comment by mithereal** [comment]
In GitHub there options under your organization settings

On Sep 7, 2017 3:43 PM, "Ryan Gaus" <notifications@github.com> wrote:

Huh. What application restrictions are you referring to? Maybe that would
help reveal the source of the problem? I can't seem to find the options you
are referring to.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/1egoman/backstroke/issues/63#issuecomment-327946851>,
or mute the thread

**Comment by 1egoman** [comment]
Fixed by https://github.com/backstrokeapp/server/issues/66
