### ISSUE TITLE
I changed the remote branch, from master to st3, but it keeps asking to merge from master

### ISSUE THREAD

**Issue by evandrocoan** [backstrokeapp/server#65]
I changed the remote branch, from master to st3, but it keeps asking to merge from master. 

The upstream was: BoundInCode/AutoFileName on branch master
The downstream is: evandrocoan/AutoFileName master

Now:

The upstream was: BoundInCode/AutoFileName on branch st3
The downstream is: evandrocoan/AutoFileName master

But when I call the hook URL, it keeps creating merge commits from the master branch, instead of st3.

Of course I saved the changes. https://github.com/evandrocoan/AutoFileName/pull/5

**Comment by 1egoman** [comment]
Hah, I think I never actually made the fork branch configurable: https://github.com/1egoman/backstroke/blob/master/src/webhook/index.js#L96

**Comment by 1egoman** [comment]
I'm in the process of pushing up quite a few changes, I'll make sure this is one of them.

**Comment by 1egoman** [comment]
Fixed by https://github.com/backstrokeapp/server/issues/66
