### ISSUE TITLE
Missing webhook URI

### ISSUE THREAD

**Issue by francescobianco** [backstrokeapp/server#73]
In new look and feel of Backstroke I did not find webhook URI to copy and paste in Upstream settings.
I suspect actually not work in automatic manner...
@francescobianco

**Comment by 1egoman** [comment]
@francescobianco Backstroke works automatically to sync your forks. You don't need to copy and paste a webhook url. Every 10 minutes, a worker attempts to sync your link if a new commit has been made to the branch configured in the link settings.

I wrote up document on how all this works, [feel free to read through it](https://github.com/backstrokeapp/server/tree/master/src/jobs/webhook-dispatcher).

**Comment by francescobianco** [comment]
Not in real-time or on-demand only every 10minutes!!! That's is too slow for continuous delivery or integrations

**Comment by francescobianco** [comment]
I used this service to keep Travis connected to a system of continuous integration into various sub-projects treated as a parent project form

**Comment by 1egoman** [comment]
@francescobianco It's economical given the number of links that are handled, and, for the typical use case this isn't that big of a deal.

The old webhooks still do work though. They currently are't shown on the dashboard (I wasn't able to get that finished prior to launching last weekend) though. If your use case does require an immediate update and you have permission to add a webhook to a repository, then you should be fine.

I'll create an issue for adding the webhook link to the link detail page on the dashboard.

**Comment by 1egoman** [comment]
If you need help in the meantime figuring out your webhook url, I can help with that. Once the feature is back on the dashboard though it shouldn't be an issue.

**Comment by francescobianco** [comment]
No problem I'm happy about this project even in this mode. Good Job!!

**Comment by 1egoman** [comment]
Thanks! Here's that issue to add the webhook link to the dashboard: https://github.com/backstrokeapp/dashboard/issues/10
