### ISSUE TITLE
About 70% of my backstroke link are missing on my backstroke dashboard

### ISSUE THREAD

**Issue by evandrocoan** [backstrokeapp/server#75]
I have all my 141 backstroke links saved on my computer and had them all on my dashboard before the upgrade, now the dashboard on shows about 27 of my repositories. They all were working just fine before the update.

So, where they got after the migration? 

In addition:

1. https://github.com/backstrokeapp/server/issues/76 I cannot ping my backstroke URLs after the migration

**Comment by 1egoman** [comment]
@evandrocoan 141 links? Wow, I didn't know one user had that many.

This is why: https://github.com/backstrokeapp/dashboard/issues/4. The dashboard currently only returns the first page of links that the server responds with, which is around 30 links if I remember correctly. It's been on my list for a while, but I'll move it closer to the top.
