### ISSUE TITLE
I cannot ping my backstroke URLs after the migration

### ISSUE THREAD

**Issue by evandrocoan** [backstrokeapp/server#76]
![image](https://user-images.githubusercontent.com/5332158/31854322-c659acfa-b675-11e7-814d-f05c47c1f310.png)

In addition to:

1. https://github.com/backstrokeapp/server/issues/75 About 70% of my backstroke link are missing on my backstroke dashboard
1. https://github.com/backstrokeapp/dashboard/issues/10 Display the webhook link on the Backstroke dashboard 

I have all my 141 backstroke links saved on my computer. They all were working just fine before the update. Now all the ones I tried are not working anymore. 

Now now they were working because I wrote a program to ping them all, and from time to time I ran it and it always had successfully completed:

1. https://github.com/evandrocoan/SublimeChannelManager/blob/1cff48955f2e38f36e350bc1d3c0ef6abe6ba333/submodules_manager.py#L302-L381

**Comment by 1egoman** [comment]
Link webhooks still kick off a manual link syncing operation at `https://backstroke.us/_linkid`; you have in your screenshot `https://backstroke.co/_linkid`. 

I discusses this and more in the RFC I put together prior to migrating - read it [here](https://github.com/backstrokeapp/server/issues/66#issue-254618293)

I replied to your other notes in the relevant tickets.
