### ISSUE TITLE
Opt-out not working

### ISSUE THREAD

**Issue by EricTendian** [backstrokeapp/server#87]
One of my company's fork repos is getting PRs as apparently the upstream repo signed up for Backstroke. I followed the [opt-out](https://github.com/backstrokeapp/server/blob/master/disable-on-a-fork.md) instructions and applied the label to [this PR](https://github.com/packbackbooks/tsugi-php/pull/4), then closed it. However, it just created a new PR so it seems like the opt-out label had no effect: https://github.com/packbackbooks/tsugi-php/pull/5

How am I supposed to stop the bot from making new PRs? Additionally, I think any unsolicited PRs made should have opt-out instructions right in the PR description, otherwise I may just decide to report/block the bot. Or even better, make it opt-in rather than opt-out.

Thanks.

**Comment by 1egoman** [comment]
The reason why that didn't work is that (currently) the opt-in mechanism only works for links that sync to a number of forks (the theory being that a upstream maintainer can turn on backstroke and any user can easily opt into to Backstroke Pull requests if they'd like).

Additionally, and I really dropped the ball on updating the documentation to reflect this, we've made the backstroke bot opt in. [here's the discussion about it if you're curious](https://github.com/backstrokeapp/server/issues/84). The reason though that backstroke was creating pull requests on your repository was that it looks like that you had logged into backstroke and created a link that syncs only to your fork - at least, that's what it looks like from within the database (I saw a link with an owner foreign that linked to a user model that had your username attached to it). The system was built with the assumption that in the process of creating a link pointing to their repository only, the user would be providing consent for backstroke to create a pull request on their repository. Maybe this should be rethought?

Here's what I did to hopefully eliminate this issue:
- Deleted the link that was syncing from the upstream to your single repository.

I'm really sorry if Backstroke was spamming your repository. It's something that I wish would never happen but it's an inevitability that backstroke will accidentally make mistakes. If Backstroke gives you any more trouble, please open another ticket and I will help you the best that I can.

**Comment by EricTendian** [comment]
Thank you for taking care of that! Good to hear the bot is now opt-in, perhaps some glitch occurred in my earlier researching of the backstroke bot to see how I could turn it off.

I haven't been getting any new PRs, so I think this issue has been resolved.
