### ISSUE TITLE
Several (if not all) of my repositories are not receiving the Pull Requests anymore

### ISSUE THREAD

**Issue by evandrocoan** [backstrokeapp/server#89]
For example: https://github.com/evandrocoan/UnitTesting is 10 commits behind the upstream, and there are not pull requests from Backstroke. Even backstroke is properly configured:

![image](https://user-images.githubusercontent.com/5332158/34608116-0357a7ec-f1fe-11e7-8308-3b65e831c448.png)

Recently the upstream has renamed from `randy3k/UnitTesting` to `SublimeText/UnitTesting`. Does it make a difference?

I also had clicked on the refresh button, but it keep spinning:

![image](https://user-images.githubusercontent.com/5332158/34608183-3c7bd19c-f1fe-11e7-9795-fbc8772dc834.png)

And accessing the ping URL https://api.backstroke.co/_59cdc241408205001... does nothing useful:

![image](https://user-images.githubusercontent.com/5332158/34608260-8f9b40a6-f1fe-11e7-97e1-5684e4fa9c53.png)

Should not accessing the ping URL https://api.backstroke.co/_59cdc241408205001... trigger the pull request creation?

**Comment by 1egoman** [comment]
> Recently the upstream has renamed from randy3k/UnitTesting to SublimeText/UnitTesting. Does it make a difference?

Try updating that. The pull request that backstroke is making returns this error code (`head` is the repository/branch that the pull request should pull changes from):
```
{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```

**Comment by evandrocoan** [comment]
Thanks, it worked!

Backstroke should have send me a email announcing this, otherwise there is not point into using backstorke if it will fails when the upstream repository is renamed/transferred to another user.

**Comment by 1egoman** [comment]
> Backstroke should have send me a email announcing this
Good idea, but that's a pretty large feature. Backstroke has no infrastructure for that right now (and frankly, I don't have time to work on something like that). Always looking for contributions though.

It should definitely fail the link operation though if the `head` isn't valid in the pull request. Not sure why it doesn't do that currently.

**Comment by evandrocoan** [comment]
Can you at least make this message say the word `Error` when it fails?

![image](https://user-images.githubusercontent.com/5332158/34613691-c9b54518-f215-11e7-9e8a-22aea8222a0c.png)

When when I run all the link I know which repositories are broken.

**Comment by evandrocoan** [comment]
Because I have this script:

https://github.com/evandrocoan/ChannelManager/blob/1c00cacce9a1d6f7b61b44afe272add5373d7936/all/channel_manager/submodules_manager.py#L439-L461

```python
            elif command == "backstroke":
                # The GitHub API only allows about 30 requests per second for the backstroke call,
                # then we make it take a little longer so all the requests can be performed in a row.
                time.sleep(2)

                # https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.get
                upstream   = self.get_section_option( section, "upstream", generalSettingsConfigs )
                backstroke = self.get_section_option( section, "backstroke", generalSettingsConfigs )

                # log( 1, upstream )
                # log( 1, backstroke )

                # https://stackoverflow.com/questions/2018026/what-are-the-differences-between-the-urllib-urllib2-and-requests-module
                if len( backstroke ) > 20:
                    successful_resquests += 1

                    # https://stackoverflow.com/questions/28396036/python-3-4-urllib-request-error-http-403
                    req = urllib.Request( backstroke, headers={'User-Agent': 'Mozilla/5.0'} )

                    try:
                        # https://stackoverflow.com/questions/2667509/curl-alternative-in-python
                        res = urllib.urlopen( req )
                        log( 1, res.read() )
```

Which iterate throw all my backstroke links on the form `https://api.backstroke.co/_59cdc241408205001...`, then I can monthly run this and catch which repositories have some kind of error.
