### ISSUE TITLE
Backstroke creates a huge pull-request

### ISSUE THREAD

**Issue by just-boris** [backstrokeapp/server#91]
Hello!

I am using Backstroke to synchronize my fork of [create-react-app](https://github.com/facebookincubator/create-react-app).

Recently something went wrong and it creates me pull-requests with commits that have been already merged. Examples:

https://github.com/just-boris/create-preact-app/pull/31
https://github.com/just-boris/create-preact-app/pull/30
https://github.com/just-boris/create-preact-app/pull/28

Github compare page says, that there is nothing to merge:
https://github.com/just-boris/create-preact-app/compare/preact...facebookincubator:master

How can I fix the issue make Backstroke show only commits that actually are not in my fork?

**Comment by 1egoman** [comment]
> Github compare page says, that there is nothing to merge: just-boris/create-preact-app@preact...facebookincubator:master

I think you were looking at the `preact` branch, this is the diff between the your repositories `master` branch (what that pull request has as it's head) and the create-react -app upstream (`facebookincubator/create-react-app@master`):
https://github.com/just-boris/create-preact-app/compare/master...facebookincubator:master

That diff does accurately reflect the commits in the pull request.

As for why there are so many changes, it might be possible that create-react-app did something interesting with their history after you forked it (such as rebasing). This isn't an issue with Backstroke - Backstroke tells Github the head and base of the pull request, and Github figures out the changes internally.

I think that if you close the pull request that backstroke creates and create a new one with the exact same base (the `master` branch) and the exact same head (`facebookincubator/create-react-app@master`) and it should have the same changes as the backstroke pull request.

Thanks for your interest in Backstroke!

**Comment by just-boris** [comment]
Hmm, I have set up backstroke to push changes into `preact` branch of my fork but it creates PRs to `master`

Can this be a root cause of my issue?

**Comment by 1egoman** [comment]
Hmm, maybe. Let me take a look at the code and see if I can find anything. I take back what I said earlier - if the pull request is being made on the wrong branch, this seems like a Backstroke problem.

**Comment by 1egoman** [comment]
Yep, turns out it was a Backstroke thing. [Here's the tiny change](https://github.com/backstrokeapp/worker/pull/10) if you're curious, but let me know if that fixed your issue.

**Comment by just-boris** [comment]
Have got a new PR from Backstroke today: https://github.com/just-boris/create-preact-app/pull/32

Works as expected, thank you!
