### ISSUE TITLE
Issue with Sync (Recived an error: undefined)

### ISSUE THREAD

**Issue by shikhir-arora** [backstrokeapp/server#97]
I apologize if I'm missing something, but I am having the following issue with any repo (on clicking 'Resync'):

`Recived an error: undefined`

![a658130e-71bc-4527-907f-f66ae1b54f26](https://user-images.githubusercontent.com/8797918/38245142-fc54c888-370a-11e8-8a91-69f9e2402e7d.png)
![e099a8ba-b338-4b1d-85b5-1be62b27360b](https://user-images.githubusercontent.com/8797918/38245143-fc62a1f6-370a-11e8-86ed-b4ec75b3a7d3.png)

Furthermore, the webhook link produces the following error:

![2e9a8f1b-ffc7-4d06-b48c-d63f9efe95f4](https://user-images.githubusercontent.com/8797918/38245175-1e39e096-370b-11e8-989c-7c94ed56028d.png)

**Comment by 1egoman** [comment]
I think I see what's going on, the redis instance that Backstroke uses seems to have run out of memory. Let me see if I can remove some old keys manually for now and later I can upgrade it to be larger.

**Comment by 1egoman** [comment]
Yep, that's exactly what happened. I'll reset it when I get back from work today.

**Comment by shikhir-arora** [comment]
Ah, well, really appreciate that. That's a good problem to have, growth is good 😆  Just put in a $2/week donation on Liberapay to help reach your goal. :-)

Thanks for the fast response and simple/useful service, and the commitment to open source. Can close this whenever you reset things.

**Comment by 1egoman** [comment]
Wow, thanks! The service should be working again - or, at least, I am able to sync a link of my own. If you run into any other issues, feel free to open another ticket.

**Comment by shikhir-arora** [comment]
Everything works fine (just had to re-auth with GitHub) -- thanks again! 👍
